query(
  $email: String
) {
  user(
    email: $email
  ){
    _id
    name
    email
    password
    codReferal
    registrationCode
    licenses{
      name
      dateStart
      dateFinish
    }
    rol
    type
    photo
    permissions
    favorites {
      tittle
      price
      description
      category
      image
      author
      date
      files
    }
    balance
    crypto
    cryptoGen
    referals
    isAdmin
    isSuperUser
    dateCreated
  }
}
