query(
  $_id: ID
) {
  userID(
    _id: $_id
  ){
    _id
    name
    email
    password
    codReferal
    registrationCode
    licenses
    rol
    type
    photo
    permissions
    balance
    crypto
    cryptoGen
    referals
    isAdmin
    isSuperUser
    dateCreated
  }
}
